### ISSUE TITLE
Support for Tubelib would be cool

### ISSUE THREAD

**Issue by joe7575** [cdqwertz/compost#2]
Tubelib (https://forum.minetest.net/viewtopic.php?f=9&t=18582) and its extensions enable automated farming and harvesting. The harvester produces wood and masses of leaves. It would be a good idea to use your compost mod to produce dirt automatically.
See https://github.com/joe7575/Minetest-Tubelib/blob/master/api.md.
If you need help, let me know.
/Joe

**Comment by cdqwertz** [comment]
I started adding some basic tubelib support: https://github.com/cdqwertz/compost/commit/24786219e1891487d0fa683a72ac849d8f5d8523#diff-d7d74284e2e39f6c06d199c8e2bedbd0 , but I still have one question: What is the `on_unpull_item` function supposed to do and when is it called?

**Comment by joe7575** [comment]
Typically you can't know, if a node inventory is full. You have to try to push an item into the inventory. If this fails (push returns false), you have to put it back by means of unpull.

I also added Tubelib support in the meantime. But the Harvester produces a lot of leaves, so I increased the composting speed by means of a node timer and decreased the output. You need 4 leaves for one compost item if you work with Tubelib support.

**Comment by cdqwertz** [comment]
Ok, so is it correct, that I do not need to define the `on_unpull_item` function in this case?  (since it is not possible to push a item into a full wood barrel)

I might increase the composting speed and use node timers instead of abms.

**Comment by joe7575** [comment]
Shall I provide you my version as blueprint?
How?

**Comment by cdqwertz** [comment]
My implementation is already working, but I just was not quite sure about the function of `on_unpull_item` function. If you want to make any improvements, you can just open a pull request.

**Comment by joe7575** [comment]
You need the on_unpull_item function. Assume the Pusher pulls a compost item from the Barrel and tries to push it into chest which is full, than it has to call unpull to put it back into the Barrel (switch back to compost:wood_barrel_2).
I upload my approach, feel free to use parts of it.

**Comment by cdqwertz** [comment]
Ok, thank you!
